#!/usr/bin/env python3
"""Collect the V6.13.0 post-A3 STRICT (OMP-swept) complex-matrix verdicts.

``scripts/recipe_multirun_gate.sh`` / ``scripts/a3_omp_one.sh`` run the two
multistable gates — opamp and ring_osc — three times per cell, at
OMP∈{1,2,4}, and write ``results/a3_regate/omp/<group>_<TECH>_<circ>.log``.
A cell is **strict-PASS** only if all three runs pass; a cell that passes some
and fails others is a **FLIP** and is not bankable (memory v648/v659, V6.6.4).

sram_snm and switchcap are deterministic under the thread pin, so their strict
verdict is taken from the single-run matrix in
``results/a3_regate/<group>/<recipe>/SUMMARY.txt``.

    strict count = strict(opamp) + strict(ring_osc) + single(sram) + single(swcap)

Usage:
    python scripts/a3_regate_omp_collect.py [--root results/a3_regate]
                                            [--out results/a3_regate/OMP_REPORT.md]
"""

from __future__ import annotations

import argparse
import re
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Optional, Tuple

TECHS: List[str] = ["TSMC5", "TSMC7", "TSMC12", "TSMC16"]
MULTISTABLE: List[str] = ["opamp", "ring_osc"]
DETERMINISTIC: List[str] = ["sram_snm", "switchcap"]

_OMP_LINE = re.compile(r"OMP=(\d+)\s*\|.*?->\s*(PASS|FAIL)")
_LOG_NAME = re.compile(r"^(?P<group>.+?)_(?P<tech>TSMC\d+)_(?P<circ>opamp|ring_osc)\.log$")


def parse_omp_log(path: Path) -> Dict[int, str]:
    """OMP value -> PASS/FAIL for one cell. Later lines win (a re-run overwrites).

    Also picks up any not-yet-folded ``<log>.omp<n>`` sidecars written by
    ``scripts/a3_omp_one.sh``, so a sweep can be collected while it is still
    running — the orchestrator only folds sidecars into the log once the whole
    pool finishes, which for the BSIM-AR cells is many hours.
    """
    out: Dict[int, str] = {}
    if path.exists():
        for line in path.read_text(errors="replace").splitlines():
            m = _OMP_LINE.search(line)
            if m:
                out[int(m.group(1))] = m.group(2)
    for sidecar in sorted(path.parent.glob(path.name + ".omp[124]")):
        m = _OMP_LINE.search(sidecar.read_text(errors="replace"))
        if m:
            out[int(m.group(1))] = m.group(2)
    return out


def strict_verdict(runs: Dict[int, str]) -> str:
    """PASS / FAIL / FLIP / PARTIAL-n for one multistable cell."""
    got = [runs[o] for o in (1, 2, 4) if o in runs]
    if len(got) < 3:
        if not got:
            return "MISSING"
        return f"PARTIAL-{len(got)}({'/'.join(got)})"
    if all(v == "PASS" for v in got):
        return "PASS"
    if all(v == "FAIL" for v in got):
        return "FAIL"
    return "FLIP"


def single_run_verdicts(root: Path, group: str) -> Dict[Tuple[str, str], str]:
    """(TECH, circ) -> PASS/FAIL from the group's single-run SUMMARY.txt."""
    out: Dict[Tuple[str, str], str] = {}
    gdir = root / group
    if not gdir.is_dir():
        return out
    for summary in gdir.glob("*/SUMMARY.txt"):
        for line in summary.read_text(errors="replace").splitlines():
            # "TSMC5 opamp | rc=0 PASS | <headline>"
            parts = line.split("|")
            head = parts[0].split()
            if len(head) != 2:
                continue
            tech, circ = head
            verdict = "PASS" if len(parts) > 1 and "rc=0 PASS" in parts[1] else "FAIL"
            out[(tech, circ)] = verdict
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default="results/a3_regate", type=Path)
    ap.add_argument("--out", default=None, type=Path)
    args = ap.parse_args()

    root: Path = args.root
    omp_dir = root / "omp"
    if not omp_dir.is_dir():
        raise SystemExit(f"no OMP directory at {omp_dir}")

    # group -> (TECH, circ) -> {omp: verdict}
    cells: Dict[str, Dict[Tuple[str, str], Dict[int, str]]] = defaultdict(dict)
    # A cell may exist only as sidecars (a resumed sweep whose pool has not
    # folded yet), so enumerate on the log name with the sidecar suffix stripped.
    names = {p.name for p in omp_dir.glob("*.log")}
    names |= {p.name.rsplit(".omp", 1)[0] for p in omp_dir.glob("*.log.omp[124]")}
    for name in sorted(names):
        m = _LOG_NAME.match(name)
        if not m:
            continue
        runs = parse_omp_log(omp_dir / name)
        if runs:
            cells[m.group("group")][(m.group("tech"), m.group("circ"))] = runs

    lines: List[str] = [
        "# V6.13.0 post-A3 re-gate — STRICT (OMP-swept) complex matrix",
        "",
        "A cell is strict-PASS only if it passes at OMP=1, 2 AND 4. `FLIP` = passes",
        "some, fails others — not bankable. `sram_snm`/`switchcap` are deterministic",
        "under the thread pin and are taken from the single-run SUMMARY.txt.",
        "",
        "Generated by `scripts/a3_regate_omp_collect.py`.",
        "",
    ]

    totals: List[Tuple[str, int, int, int]] = []
    for group in sorted(cells):
        single = single_run_verdicts(root, group)
        lines += [f"## {group}", "", "| tech | opamp (strict) | ring_osc (strict) | sram_snm | switchcap |",
                  "|---|---|---|---|---|"]
        strict_pass = 0
        flips = 0
        missing = 0
        for tech in TECHS:
            row = [tech]
            for circ in MULTISTABLE:
                runs = cells[group].get((tech, circ))
                v = strict_verdict(runs) if runs else "MISSING"
                if v == "PASS":
                    strict_pass += 1
                elif v == "FLIP":
                    flips += 1
                elif v == "MISSING" or v.startswith("PARTIAL"):
                    missing += 1
                row.append(v)
            for circ in DETERMINISTIC:
                v = single.get((tech, circ), "—")
                if v == "PASS":
                    strict_pass += 1
                elif v == "—":
                    missing += 1
                row.append(v)
            lines.append("| " + " | ".join(row) + " |")
        note = []
        if flips:
            note.append(f"**{flips} FLIP**")
        if missing:
            note.append(f"{missing} not yet measured")
        suffix = f"  ({', '.join(note)})" if note else "  (zero flips)"
        lines += ["", f"**strict {strict_pass}/16**{suffix}", ""]
        totals.append((group, strict_pass, flips, missing))

    lines += ["## Summary", "", "| group | strict /16 | flips | unmeasured |", "|---|---|---|---|"]
    for group, sp, fl, ms in sorted(totals, key=lambda t: (-t[1], t[0])):
        lines.append(f"| {group} | {sp} | {fl} | {ms} |")
    lines.append("")

    text = "\n".join(lines)
    out = args.out or (root / "OMP_REPORT.md")
    out.write_text(text)
    print(text)
    print(f"\n[written] {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
