#!/usr/bin/env python3
"""V6.7 — append the transmission-gate / pass-device corridor to a dataset.

Adds the ``tg_corridor`` sample class (code 13) to an existing per-tech .npz.
For every (variant, NFIN, L, T) bin already present in the dataset, OSDI-evaluates
the ``_tg_corridor_points`` loci (deep-reverse-Vds × large-body-bias gap-fill —
see ``pycmg/nn_generate._tg_corridor_points``) and appends format-identical
rows (inputs [Vd,Vg,0,Vbs] / 15-col geometry / 13-col outputs / sample_class).
The new geometry row REUSES the bin's existing geometry row so process-param
columns stay byte-consistent with the rest of the dataset.

Ground truth = OSDI eval_dc (CLAUDE.md Validation rule). NOT generated by
``generate_one_bin`` — this is a post-hoc overlay like ``traj_corridor``.

Usage:
    python scripts/v6_7_append_tg_corridor.py --tech tsmc5 --device nmos \
        --in  external_compact_models/bsimar/data/datasets/tsmc5_nmos.npz \
        --out external_compact_models/bsimar/data/datasets/tsmc5_tg_nmos.npz \
        --workers 8
"""
from __future__ import annotations

import argparse
import functools
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np

print = functools.partial(print, flush=True)  # type: ignore[assignment]

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "external_compact_models"))
sys.path.insert(0, str(PROJECT_ROOT / "external_compact_models" / "PyCMG"))

from pycmg.nn_config import TECH_CONFIGS, OUTPUT_COLUMNS  # noqa: E402
from pycmg.nn_generate import (  # noqa: E402
    SAMPLE_CLASS_NAMES, SAMPLE_CLASS_CODES,
    _create_model_and_instance, _tg_corridor_points, eval_single_point,
)
from bsimar.config import CODE_TO_TECH_VARIANT  # noqa: E402

_NN_OUT = OUTPUT_COLUMNS  # 13-col order matching the dataset 'outputs'


def _variant_of(code: int) -> Optional[str]:
    """Universal tech_code -> variant name (None if cross-tech)."""
    tv = CODE_TO_TECH_VARIANT.get(int(code))
    return tv[1] if tv is not None else None


def _eval_bin(task: Tuple) -> Optional[Dict[str, np.ndarray]]:
    tech_name, device, variant, NFIN, L, T, geo_row, vdd, is_pmos = task
    built = _create_model_and_instance(
        TECH_CONFIGS[tech_name], device, variant, float(L), float(NFIN), float(T))
    if built is None:
        return None
    _m, inst, _proc = built
    pts = _tg_corridor_points(vdd, is_pmos)
    cls = SAMPLE_CLASS_CODES["tg_corridor"]
    inputs, geometry, outputs, classes = [], [], [], []
    for vg, vd, vbs in pts:
        r = eval_single_point(inst, vd=float(vd), vg=float(vg), vs=0.0, vb=float(vbs))
        if r is None:
            continue
        inputs.append(np.array([vd, vg, 0.0, vbs], dtype=np.float64))
        geometry.append(np.asarray(geo_row, dtype=np.float64))
        outputs.append(np.array([r[k] for k in _NN_OUT], dtype=np.float64))
        classes.append(cls)
    if not inputs:
        return None
    return {"inputs": np.stack(inputs), "geometry": np.stack(geometry),
            "outputs": np.stack(outputs),
            "sample_class": np.array(classes, dtype=np.int8)}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tech", required=True)
    ap.add_argument("--device", required=True, choices=["nmos", "pmos"])
    ap.add_argument("--in", dest="inp", required=True)
    ap.add_argument("--out", dest="out", required=True)
    ap.add_argument("--workers", type=int, default=8)
    args = ap.parse_args()

    tech_name, device = args.tech, args.device
    is_pmos = device == "pmos"
    vdd = float(TECH_CONFIGS[tech_name].vdd)

    print(f"Loading {args.inp} …")
    d = np.load(args.inp, allow_pickle=True)
    inp, geo, out = d["inputs"], d["geometry"], d["outputs"]
    n0 = len(inp)
    if "sample_class" in d.files:
        sc = np.asarray(d["sample_class"], dtype=np.int8)
    else:
        sc = np.full(n0, SAMPLE_CLASS_CODES["lhs"], dtype=np.int8)

    from bsimar.eval.loo_labels import get_or_build_tech_variant_labels
    codes = get_or_build_tech_variant_labels(args.inp, device, verbose=False)

    # Enumerate unique (code, NFIN, L, T) bins via np.unique (O(n log n)); reuse
    # each bin's existing geometry row so process-param columns stay consistent.
    key_arr = np.stack(
        [codes.astype(np.float64), geo[:, 0], geo[:, 1], geo[:, 2]], axis=1)
    _uniq, first_idx = np.unique(key_arr, axis=0, return_index=True)
    bins: Dict[Tuple, np.ndarray] = {}
    for ridx in first_idx:
        variant = _variant_of(int(round(codes[ridx])))
        if variant is None:
            continue
        key = (variant, float(geo[ridx, 0]), float(geo[ridx, 1]),
               float(geo[ridx, 2]))
        if key not in bins:
            bins[key] = geo[ridx].copy()
    print(f"  {n0} rows, {len(bins)} unique (variant,NFIN,L,T) bins")
    pts0 = _tg_corridor_points(vdd, is_pmos)
    print(f"  tg_corridor loci/bin (gap-filtered): {len(pts0)}  "
          f"(VDD={vdd}, {'PMOS' if is_pmos else 'NMOS'})")

    tasks = [(tech_name, device, v, nf, L, T, g, vdd, is_pmos)
             for (v, nf, L, T), g in bins.items()]

    results: List[Optional[Dict[str, np.ndarray]]] = []
    if args.workers > 1:
        import multiprocessing as mp
        with mp.Pool(args.workers) as pool:
            for j, r in enumerate(pool.imap_unordered(_eval_bin, tasks)):
                results.append(r)
                if (j + 1) % 10 == 0:
                    print(f"  …{j + 1}/{len(tasks)} bins")
    else:
        for j, t in enumerate(tasks):
            results.append(_eval_bin(t))
            if (j + 1) % 10 == 0:
                print(f"  …{j + 1}/{len(tasks)} bins")

    new = [r for r in results if r is not None]
    if not new:
        print("  No tg_corridor rows generated (all bins failed?) — aborting.")
        return 1
    add_in = np.concatenate([r["inputs"] for r in new])
    add_geo = np.concatenate([r["geometry"] for r in new])
    add_out = np.concatenate([r["outputs"] for r in new])
    add_sc = np.concatenate([r["sample_class"] for r in new])
    print(f"  generated {len(add_in)} tg_corridor rows "
          f"({100.0 * len(add_in) / n0:.1f}% of base)")

    meta = {k: d[k] for k in d.files
            if k.startswith("meta_") and k != "meta_sample_class_names"}
    meta["meta_sample_class_names"] = np.array(SAMPLE_CLASS_NAMES, dtype=object)

    out_data = dict(
        inputs=np.concatenate([inp, add_in]),
        geometry=np.concatenate([geo, add_geo]),
        outputs=np.concatenate([out, add_out]),
        sample_class=np.concatenate([sc, add_sc]),
        **meta,
    )
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    np.savez(args.out, **out_data)
    print(f"  wrote {args.out}: {len(out_data['inputs'])} rows "
          f"({n0} + {len(add_in)})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
