"""Run one AnalogGym deck through BOTH simulators and score them side by side.

This is the layer that closes the loop: ``translate`` turns a deck into a
PyCircuitSim netlist plus :class:`AnalysisPlan` data, ``measure`` turns a
:class:`SweepResult` into metrics, and this module produces the two
``SweepResult``s -- one per simulator -- and puts three metric columns next to
each other:

``py``
    ``measure`` over PyCircuitSim's own solve.
``ng``
    ``measure`` over NGSPICE's solve, read back from an ASCII rawfile dumped by
    the reference runner (``tools/meas.run_deck``).
``ng_meas``
    NGSPICE's OWN ``.meas`` values from the same run.

``py`` vs ``ng`` is the number that matters: both go through one measurement
implementation, so a difference there is physics or numerics and can never be a
difference in what ``AVG from=-40 to=125`` was taken to mean.  ``ng`` vs
``ng_meas`` is the control that proves the measurement engine agrees with
NGSPICE on NGSPICE's own data; if that column disagrees, nothing else in the
row can be trusted.

Only LEVEL=72 (BSIM-CMG via PyCMG/OSDI) is involved.  No NN model family
(LEVEL=73/74/75) is imported, instantiated or invoked.

DC QUALITY IS THE WHOLE GAME
----------------------------
A probe established that PyCircuitSim's AC machinery is essentially exact --
solved about NGSPICE's operating point the pilot amplifier's dcgain lands within
0.004 dB and its GBW ratio at 1.0000 -- and that the entire error budget is the
DC operating point.  Two consequences are baked into this module:

* ``DCSolver._last_solve_converged`` is NOT accepted as evidence.  The
  operating-point delta against NGSPICE is a first-class output field
  (``op_delta``), computed node by node: for a dc sweep over EVERY solved
  point, for ac/tran against a dedicated NGSPICE ``op`` run.  A metric that
  matches for the wrong reason is worse than a reported failure.
* the DC solve is seeded from the deck's own ``.nodeset`` and run with the
  ``dv_limit`` trust region (see :data:`DEFAULT_MAX_ITERATIONS` and
  ``DCSolver(dv_limit=...)``), because without a per-iteration voltage cap the
  LEVEL=72 path hands OSDI a gate voltage of -505225 V and the compact model
  raises.

Both simulators' grids are generated by NGSPICE's own algorithms
(:func:`plan_points`), verified against real dumps: a decade AC sweep by
repeated multiplication (agrees to 4.3e-16), a dc sweep as
``floor((stop-start)/step) + 1`` accumulated points (which is why ``dc temp 25
20 -0.1`` stops at 20.1 and not at 20.0, in both simulators).

MEASURED STATE (tsmc5 pilot, one deck per family)
-------------------------------------------------
What this module found, so the next reader does not re-derive it:

* ``amplifier/Alfio_RAFFC_Pin_3/tb_gain.cir`` (AC, 24 devices, 221 points) --
  8/8 metrics agree; dcgain to 3.9e-5 relative, GBW to 6.9e-6, true phase
  margin to 3.1e-7.  Operating point within 110 uV worst / 25 uV rms of NGSPICE
  over all 19 nodes.  2.15 s against NGSPICE's 0.32 s.
  ``ldo/ldo_1/tb_loop_max.cir`` behaves the same way (8/8, 8.1 s, operating
  point within 91 uV) with ONE outlier worth watching: its ``dcgain_max`` reads
  75.33 dB against 74.12 dB, a 1.6 % relative gap that passes the 2 % default
  but is four orders of magnitude looser than every other AC metric measured.
* ``ldo/ldo_1/tb_load.cir`` (dc source sweep, 101 points) -- 11/11 metrics
  agree; operating point within 148 uV worst / 23 uV rms over 1111 node
  comparisons.  At PyCircuitSim's OWN tolerances (RELTOL 1e-4) the same run
  produced the same values while its convergence flag rejected all 101 points;
  at NGSPICE's tolerances all 101 pass.  Hence :data:`NGSPICE_RELTOL`, and hence
  the flag being reported rather than obeyed.  681 s against NGSPICE's 0.29 s.
* ``sensing_front_end/ptat_1/tb_dc.cir`` (dc temp, 281 points) -- agrees above
  ~50 C (vout50 to 2e-5) and is wrong below it, because PyCircuitSim's LEVEL=72
  returns EXACTLY 0 A at NGSPICE's own operating point once Vgs falls under
  ~60 mV (measured: id = 0.0 A at Vgs = 55.3 mV, id = 2.16 nA at Vgs =
  61.9 mV).  A weak-inversion stack whose devices all read zero current has no
  operating point to find, so the whole PTAT / voltage-reference family is
  blocked on that floor, not on anything here.
* ``charge_pump/chargepump/tb_tran.cir`` (transient, 41 devices) -- dies at the
  FIRST timestep at every dt tried (2 ps, 20 ps, 200 ps, 1 ns), with NR pinned
  at the ``dv_limit`` cap for all 200 iterations.  A per-iteration node-delta
  cap bounds the STEP, not the terminal voltage, so six capped iterations still
  walk a gate to -2.96 V and a drain to +3.94 V on a 0.65 V rail and OSDI
  rejects it.  Fixing this needs SPICE-style per-terminal limiting inside
  ``models/mosfet_cmg.py`` (bound Vgs/Vds/Vbs themselves), which does not exist:
  the LEVEL=72 path hands OSDI raw node voltages.
* ``amplifier/Alfio_RAFFC_Pin_3/tb_dc.cir`` (dc temp, 1651 points, run at
  ``--stride 25``) -- 0/15 metrics, and the ``op_delta`` says why rather than
  leaving it to be guessed: 9.75 V worst / 2.25 V rms node error on a 0.65 V
  rail, ``ivdd25`` of 17 kA.  The FIRST point of this bench is 125 C
  (``dc temp 125 -40 -0.1``) and it diverges there, after which the
  continuation carries the garbage down the whole sweep.  Same subcircuit,
  same devices, as the ``tb_gain`` deck that agrees to 4e-5 -- so this is the
  bench's Newton start, not the model.  ``finalize.py`` hits the same wall in
  NGSPICE on some designs and answers it by sweeping OUTWARD from the qualified
  25 C point; :func:`translate.recovery_decks` already emits exactly those
  segments, and wiring them in is the obvious next step for this family.
* ``amplifier/.../tb_tran.cir`` (transient, at ``--stride 20``) -- transients are
  NOT uniformly broken: this one commits 119 of 221 steps and its settled levels
  match NGSPICE to 3e-7 (``v_pre``, ``v_high``), then NR exhausts on the falling
  slew edge and the partial waveform is recovered and measured.  The slew
  metrics are off by 21 % because ``--stride 20`` asks for a 100 ns timestep on a
  deck written for 5 ns; that is the stride, not the simulator.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import sys
import time
from dataclasses import asdict, dataclass, replace
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np

from . import (
    CONTROLS,
    SCHEMA_VERSION,
    AnalysisPlan,
    MetricDict,
    SimFailure,
    SweepResult,
    TranslatedDeck,
)
from . import measure as measure_mod
from . import translate

# ── Repository wiring ────────────────────────────────────────────────────

#: ``examples/complex_circuits`` -- the tree holding ``designs_tsmc*``.
BENCH_ROOT: Path = Path(__file__).resolve().parents[1]

#: Repository root (four levels up from this file: pycircuitsim_bench ->
#: analoggym -> examples -> repo).
REPO_ROOT: Path = BENCH_ROOT.parents[1]

#: The reference runner lives in the TSMC5 tree and is tech-agnostic apart from
#: the OSDI path, which is resolved from the repo root.  Importing it (rather
#: than reimplementing ``ngspice -b`` invocation) is deliberate: the ``ng``
#: column has to come from the same code path the scored artifacts came from.
_TOOLS_DIR: Path = BENCH_ROOT / "tools"

for _p in (str(REPO_ROOT), str(BENCH_ROOT), str(_TOOLS_DIR.parent), str(_TOOLS_DIR)):
    if _p not in sys.path:
        sys.path.insert(0, _p)


# ── Defaults ─────────────────────────────────────────────────────────────

#: NR iteration budget per DC point.  ``DCSolver`` splits this across source
#: steps (``max_iterations // num_steps``), so the default 50 gives TWO
#: iterations per step with source stepping on -- which cannot solve a 90 dB
#: amplifier.  Source stepping is off here (measured: it costs 25 s and changes
#: nothing once ``dv_limit`` is on), so this is the per-point budget.
DEFAULT_MAX_ITERATIONS: int = 500

#: Absolute agreement floors for metrics whose RELATIVE comparison explodes
#: on near-zero values (V7.5.3).  ``vos25 = vout25 - 0.195`` subtracts two
#: near-equal numbers: the underlying node agrees to a few uV (rel ~4e-6)
#: yet the difference reaches the 2 % gate at ~1e4 amplification; 10 uV is
#: ~15 ppm of the 0.65-0.8 V rails.  The LDO load-step ``overshoot`` /
#: ``undershoot`` are mV-scale excursions when they exist at all —
#: ldo_folded_cascode reports 2.4e-10 V against NGSPICE's 8.0e-10 V (rel
#: 0.70, both meaning "the output does not move"); below a microvolt the
#: two simulators are saying the same thing.
METRIC_ATOL: Dict[str, float] = {"vos25": 1e-5,
                                 "overshoot": 1e-6, "undershoot": 1e-6}

#: NGSPICE-45.2's own DC convergence tolerances.  PyCircuitSim defaults to
#: RELTOL=1e-4 / VNTOL=1e-7 -- TEN TIMES TIGHTER than the simulator it is being
#: compared against -- and on these decks the tighter test is what fails, not the
#: physics: measured on the LDO load bench, all 101 points burn the full NR
#: budget and report non-convergence while every value agrees with NGSPICE to
#: ~2e-5.  Comparing two simulators on the same circuit means asking them to
#: solve it to the same standard, so the bench matches NGSPICE.  A deck's own
#: ``.options reltol/vntol`` still wins over both.
NGSPICE_RELTOL: float = 1e-3
NGSPICE_VNTOL: float = 1e-6

#: ``I(...)`` of the LDO line-regulation output; the two ``tb_line`` decks carry
#: no ``.meas`` cards at all and the reference computes their metrics in an
#: ngspice control block over ``dc1.v(vo)`` / ``dc2.v(vo)``.
LINE_NODE: str = "vo"

#: ``AnalysisPlan.kind`` -> ``SweepResult.kind``. NOT the identity: a plan
#: distinguishes ``dc_source`` from ``dc_temp`` (they are executed differently),
#: while a ``.meas`` card only ever says ``dc`` — and ``measure`` evaluates a
#: card only against a result of its OWN analysis, so getting this wrong scores
#: every dc deck as zero measurements rather than as a mismatch.
_RESULT_KIND: Dict[str, str] = {
    "ac": "ac", "tran": "tran", "dc_source": "dc", "dc_temp": "dc",
}

#: Node names in an NGSPICE rawfile containing this are OSDI-internal device
#: nodes (``v(n.xop1.nm0#di)``).  PyCircuitSim keeps those inside the OSDI
#: instance, so they exist on one side only and are excluded from the
#: operating-point comparison rather than counted as missing.
_INTERNAL_MARK: str = "#"


@dataclass(frozen=True)
class SimOptions:
    """Everything that changes what the PyCircuitSim side does.

    ``dv_limit`` of ``None`` means "derive it from the deck": the largest
    voltage-source magnitude in the circuit, i.e. one supply rail, which is the
    cap the NN path already uses.  ``0.0`` disables the trust region (and
    reproduces the divergence, which is why it is expressible).

    ``stride`` subsamples a sweep axis (and multiplies the transient timestep)
    so an 1651-point pure-Python temperature sweep can be measured at a
    tractable cost.  It keeps the FULL range -- only the grid gets coarser -- so
    every ``.meas`` window still covers what it was written to cover; the value
    is recorded in the result JSON so a strided row can never be mistaken for a
    full-resolution one.
    """

    dv_limit: Optional[float] = None
    max_iterations: int = DEFAULT_MAX_ITERATIONS
    use_source_stepping: bool = False
    reltol: float = NGSPICE_RELTOL
    vntol: float = NGSPICE_VNTOL
    stride: int = 1
    max_seconds: Optional[float] = None
    ng_timeout: float = 1800.0


# ── NGSPICE grid reproduction ────────────────────────────────────────────

def plan_points(plan: AnalysisPlan, stride: int = 1) -> np.ndarray:
    """The sweep abscissa NGSPICE would use for *plan*.

    * ``ac dec n f1 f2``: ``f1`` multiplied repeatedly by ``10**(1/n)`` while
      the product stays ``<= f2``.  Verified against a real dump (0.1 .. 10G,
      dec 20): 221 points, agreeing to 4.3e-16 relative.  Computing the same
      grid as ``f1 * 10**(k/n)`` agrees only to 1.9e-14 and puts a 20-ulp wedge
      between the two simulators' abscissae.
    * ``dc`` (source or temp): ``floor((stop-start)/step) + 1`` points,
      accumulated by repeated addition.  Verified against real dumps:
      ``dc temp 25 20 -0.1`` gives 50 points ending at 20.09999999999889 (NOT
      51 ending at 20.0, because ``-5/-0.1`` is 49.999999999999993 in IEEE-754),
      and ``dc temp -40 125 0.5`` gives 331.
    * ``tran``: ``0, dt, 2*dt, ...`` up to ``t_stop``.  This is PyCircuitSim's
      fixed-step grid, NOT NGSPICE's -- NGSPICE writes its own internally
      adapted timepoints, so the two transient abscissae genuinely differ and
      the comparison happens at the metric level.

    Args:
        plan: The analysis to generate points for
        stride: Keep every *stride*-th point (transient: multiply dt instead)

    Returns:
        The abscissa as a float array

    Raises:
        SimFailure: On an unknown plan kind or a degenerate sweep
    """
    if stride < 1:
        raise SimFailure(f"stride must be >= 1, got {stride}")

    if plan.kind == "ac":
        assert plan.f_start is not None and plan.f_stop is not None
        assert plan.n_per_decade is not None
        if plan.f_start <= 0.0:
            raise SimFailure(f"AC sweep must start above 0 Hz: {plan.control}")
        delta = math.exp(math.log(10.0) / plan.n_per_decade)
        out = [plan.f_start]
        freq = plan.f_start
        while True:
            freq = freq * delta
            if freq > plan.f_stop:
                break
            out.append(freq)
        points = np.array(out, dtype=np.float64)

    elif plan.kind in ("dc_source", "dc_temp"):
        assert plan.start is not None and plan.stop is not None
        assert plan.step is not None
        # V7.5.3 — NGSPICE's own termination rule (dctrcurv.c): accumulate
        # the swept value and emit while sgn(step)*(value - stop) <=
        # 1000*DBL_EPSILON, an ABSOLUTE tolerance. Temperature sweeps
        # accumulate in KELVIN (CKTtemp += step; the recorded point is
        # CKTtemp - 273.15), so their accumulated error is Kelvin-scale
        # (~5.7e-14 per step) and the same rule drops an endpoint a source
        # sweep keeps. The former floor((stop-start)/step)+1 count matched
        # dumps only while the quotient floated below the next integer:
        # `dc temp 125 -40 -0.1` produced 1651 points against NGSPICE's
        # 1650, with a final abscissa a few ulp OUTSIDE the deck's
        # `.meas from=-40` edge (= a whole endpoint sample lost to the
        # sample-exact window rule). Verified point-for-point against real
        # dumps: HoiLee tb_dc 1650/1650 (worst deviation one Kelvin ulp =
        # the rawfile's print precision), ldo tb_load 101/101 keeping the
        # 0.05500000000000004 endpoint, `dc temp 25 20 -0.1` still stops
        # at 20.1, exact-step sweeps (0.5 C) keep their endpoints exactly.
        sgn = 1.0 if plan.step > 0 else -1.0
        tol = 1e3 * sys.float_info.epsilon
        kelvin = 273.15 if plan.kind == "dc_temp" else 0.0
        value = plan.start + kelvin
        out = []
        while True:
            point = value - kelvin
            if sgn * (point - plan.stop) > tol:
                break
            out.append(point)
            value = value + plan.step
        if not out:
            raise SimFailure(f"Sweep step points away from stop: {plan.control}")
        points = np.array(out, dtype=np.float64)

    elif plan.kind == "tran":
        assert plan.t_step is not None and plan.t_stop is not None
        dt = plan.t_step * stride
        n_intervals = int(math.ceil(plan.t_stop / dt - 1e-9))
        points = np.minimum(np.arange(n_intervals + 1) * dt, plan.t_stop)
        return points                      # stride already applied via dt

    else:
        raise SimFailure(f"Cannot generate points for plan kind {plan.kind!r}")

    if stride > 1:
        # Keep the endpoints: the last point carries a measurement window edge.
        keep = list(range(0, len(points), stride))
        if keep[-1] != len(points) - 1:
            keep.append(len(points) - 1)
        points = points[keep]
    return points


# ── NGSPICE side ─────────────────────────────────────────────────────────

def read_rawfile(path: Path) -> Tuple[str, List[str], np.ndarray]:
    """Parse an NGSPICE ASCII rawfile into ``(plotname, names, values)``.

    ``values`` is ``(npoints, nvars)``, complex for a ``Flags: complex`` plot.
    The point-index token NGSPICE writes before each row is verified against the
    expected index rather than skipped by pattern, so a truncated dump is an
    error instead of a silently misaligned table.

    Raises:
        SimFailure: If the file is missing, holds more than one plot, or its
            token count does not match the declared shape
    """
    if not path.exists():
        raise SimFailure(f"NGSPICE wrote no rawfile at {path}")
    lines = path.read_text().splitlines()

    plotname = ""
    n_vars = n_points = -1
    is_complex = False
    names: List[str] = []
    values_at = -1
    for idx, line in enumerate(lines):
        low = line.lower()
        if low.startswith("plotname:"):
            if plotname:
                raise SimFailure(
                    f"{path} holds more than one plot; the dump must be one "
                    f"analysis so its abscissa is unambiguous")
            plotname = line.split(":", 1)[1].strip()
        elif low.startswith("flags:"):
            is_complex = "complex" in low
        elif low.startswith("no. variables:"):
            n_vars = int(line.split(":", 1)[1])
        elif low.startswith("no. points:"):
            n_points = int(line.split(":", 1)[1])
        elif low.startswith("variables:"):
            for var_line in lines[idx + 1:]:
                if var_line.lower().startswith("values:"):
                    break
                parts = var_line.split()
                if len(parts) < 2:
                    raise SimFailure(f"{path}: malformed variable line {var_line!r}")
                names.append(parts[1].lower())
        elif low.startswith("values:"):
            values_at = idx + 1
            break
    if values_at < 0 or n_vars < 0 or n_points < 0:
        raise SimFailure(f"{path}: incomplete rawfile header")
    if len(names) != n_vars:
        raise SimFailure(f"{path}: declares {n_vars} variables, lists {len(names)}")

    tokens: List[str] = []
    for line in lines[values_at:]:
        tokens.extend(line.split())
    expected = n_points * (n_vars + 1)
    if len(tokens) != expected:
        raise SimFailure(
            f"{path}: {len(tokens)} value tokens but {n_points} points x "
            f"({n_vars} vars + 1 index) = {expected} -- truncated dump?")

    dtype = np.complex128 if is_complex else np.float64
    values = np.zeros((n_points, n_vars), dtype=dtype)
    cursor = 0
    for point in range(n_points):
        if int(tokens[cursor]) != point:
            raise SimFailure(
                f"{path}: expected row index {point}, found {tokens[cursor]!r}")
        cursor += 1
        for var in range(n_vars):
            token = tokens[cursor]
            cursor += 1
            if is_complex:
                real, imag = token.split(",")
                values[point, var] = complex(float(real), float(imag))
            else:
                values[point, var] = float(token)
    return plotname, names, values


def raw_to_sweep(path: Path, kind: str) -> SweepResult:
    """Turn an NGSPICE ASCII rawfile into a :class:`SweepResult`.

    Variable ``v(x)`` becomes ``v["x"]`` and ``i(x)`` becomes ``i["x"]``; the
    first variable is the abscissa.  Every point in a rawfile is a solved point,
    so ``ok`` is ``None``.
    """
    plotname, names, values = read_rawfile(path)
    x_name = names[0]
    v: Dict[str, np.ndarray] = {}
    i: Dict[str, np.ndarray] = {}
    for col, name in enumerate(names[1:], start=1):
        if name.startswith("v(") and name.endswith(")"):
            v[name[2:-1]] = values[:, col]
        elif name.startswith("i(") and name.endswith(")"):
            i[name[2:-1]] = values[:, col]
        # Anything else (a second sweep column, a raw device operating-point
        # variable) is not addressable by a .meas card and is dropped.
    x = np.real(values[:, 0]).astype(np.float64)
    return SweepResult(kind=kind, x_name=x_name, x=x, v=v, i=i, ok=None,
                       source="ngspice", meta={"plotname": plotname,
                                               "rawfile": str(path)})


def _pin_design_tree(root: Path, tech: str) -> None:
    """Tell the shared ``tools/`` which design tree this run is scoring.

    V7.5.8 replaced the five per-tech ``designs_tsmc*/tools/`` copies with one
    shared directory, so ``pycmg_lib._resolve_tree()`` no longer infers the
    tech from its own location: it reads ``AG_TREE``, then ``AG_TECH``, then
    the working directory, and RAISES when none resolve. ``run_compare`` is
    invoked from the repository root (``python -m examples...``), which is
    none of those — so every deck died at ``from meas import run_deck`` with
    "Cannot tell which design tree to use" until V7.5.9. ``--tech`` already
    names the tree unambiguously; pin it before the lazy import can fire.

    ``AG_TREE`` wins over ``AG_TECH`` in the resolver, so setting it here also
    overrides a stale ``AG_TECH`` inherited from the caller's environment,
    which would otherwise score one tech's decks against another's modelcards.
    """
    os.environ["AG_TREE"] = str((root / f"designs_{tech.lower()}").resolve())


def _run_ngspice(deck: Path, control: str, work: Path, tag: str,
                 timeout: float) -> MetricDict:
    """``tools/meas.run_deck``, imported lazily so the module stays importable.

    The reference runner needs ``pycmg_lib`` on ``sys.path`` and an OSDI binary
    on disk; importing it at module scope would make ``run_compare`` unimportable
    on a machine without them, including for ``--help``.
    """
    from meas import run_deck                                   # noqa: PLC0415
    return run_deck(deck, control, work, tag, timeout=timeout)


def ngspice_sweep(td: TranslatedDeck, plan: AnalysisPlan, work: Path,
                  timeout: float) -> Tuple[SweepResult, MetricDict, float]:
    """Run one plan through NGSPICE, returning ``(sweep, own_meas, seconds)``.

    The dump is appended to the control exactly the way ``tools/acstab.py``
    appends its ``wrdata`` -- same runner, same OSDI binary, same ``.meas``
    parsing -- except that an ASCII rawfile is written instead of three columns,
    so EVERY node voltage and branch current comes back and the same measurement
    code can be pointed at it.
    """
    tag = f"{Path(td.deck).stem}{'_' + plan.label if plan.label else ''}"
    raw = (work / f"{tag}.raw").resolve()
    raw.unlink(missing_ok=True)
    control = f"{plan.control}\nset filetype=ascii\nwrite {raw} all"
    started = time.perf_counter()
    own = _run_ngspice(td.design_dir / td.deck, control, work, tag, timeout)
    seconds = time.perf_counter() - started
    return raw_to_sweep(raw, _RESULT_KIND[plan.kind]), own, seconds


def ngspice_operating_point(td: TranslatedDeck, work: Path,
                            timeout: float) -> Dict[str, float]:
    """NGSPICE's DC operating point for this deck, node -> volts.

    Its own pass, because an ac/tran dump carries no operating point.  Internal
    OSDI device nodes are dropped: they have no PyCircuitSim counterpart.
    """
    raw = (work / f"{Path(td.deck).stem}_op.raw").resolve()
    raw.unlink(missing_ok=True)
    control = f"op\nset filetype=ascii\nwrite {raw} all"
    _run_ngspice(td.design_dir / td.deck, control, work,
                 f"{Path(td.deck).stem}_op", timeout)
    _, names, values = read_rawfile(raw)
    out: Dict[str, float] = {}
    for col, name in enumerate(names):
        if name.startswith("v(") and name.endswith(")"):
            node = name[2:-1]
            if _INTERNAL_MARK in node:
                continue
            out[node] = float(np.real(values[0, col]))
    return out


# ── PyCircuitSim side ────────────────────────────────────────────────────

def build_circuit(td: TranslatedDeck, work: Path):
    """Parse the translated netlist into a PyCircuitSim ``Circuit``.

    The netlist is written to disk first (``translate.write_netlist``) because
    ``Parser`` only reads files -- and because the artifact is what an audit of
    a disagreement starts from.

    Returns:
        ``(circuit, netlist_path)``
    """
    from pycircuitsim.parser import Parser                      # noqa: PLC0415

    path = translate.write_netlist(td, work / "netlists")
    parser = Parser(modelcard_path=str(td.modelcard_path))
    parser.parse_file(str(path))
    return parser.circuit, path


def _fail(meta: Dict[str, Any], message: str) -> "SimFailure":
    """A :class:`SimFailure` carrying the partial ``meta`` it died with.

    A transient that dies at step 1 is the case where the operating-point delta
    matters MOST -- it is the diagnosis -- and it is exactly the case where the
    sweep does not exist to carry it. So the meta rides on the exception and
    ``compare_translated`` recovers the operating point from there.
    """
    error = SimFailure(message)
    error.partial_meta = meta                   # type: ignore[attr-defined]
    return error


def _mosfets(circuit) -> list:
    """Every LEVEL=72 device in the circuit (the only devices we ever touch)."""
    from pycircuitsim.models.mosfet_cmg import MOSFET_CMG       # noqa: PLC0415
    return [c for c in circuit.components if isinstance(c, MOSFET_CMG)]


def _supply_rail(circuit) -> float:
    """Largest voltage-source magnitude, i.e. one supply rail (>= 1e-3 V)."""
    from pycircuitsim.models.passive import VoltageSource       # noqa: PLC0415
    rails = [abs(c.voltage) for c in circuit.components
             if isinstance(c, VoltageSource)]
    return max([r for r in rails if r > 0.0] + [1e-3])


def _node_table(circuit) -> Dict[str, str]:
    """``lower-cased node -> circuit node``, raising on a case collision.

    Node names are lower-cased on the way out because that is what NGSPICE and
    every ``.meas`` card use, and because ``translate`` keeps the X-instance
    name's case while flattening (``Xop1.vb4`` against NGSPICE's ``xop1.vb4``).
    """
    table: Dict[str, str] = {}
    for node in circuit.get_nodes():
        low = node.lower()
        if low in table and table[low] != node:
            raise SimFailure(
                f"Nodes {table[low]!r} and {node!r} differ only in case; "
                f"lower-casing for the NGSPICE comparison would merge them")
        table[low] = node
    return table


def _branch_sources(circuit) -> Dict[str, Any]:
    """``lower-cased source name -> VoltageSource`` (what ``i(x)`` can read)."""
    from pycircuitsim.models.passive import VoltageSource       # noqa: PLC0415
    out: Dict[str, Any] = {}
    for comp in circuit.components:
        if isinstance(comp, VoltageSource):
            out[comp.name.lower()] = comp
    return out


def _apply_temperature(circuit, temp_c: float) -> None:
    """Rebind every device at *temp_c*, in place.

    PyCircuitSim has no temperature-sweep directive, so a ``dc temp`` sweep is
    executed by rebinding the devices per point.  ``Instance.set_temperature``
    exists for exactly this: measured 0.255 ms/device against 808.8 ms to
    rebuild one, and bit-identical to a freshly constructed instance at that
    temperature.  It also clears the voltage-keyed eval cache, without which a
    temperature change at unchanged voltages would return the previous point's
    answer.
    """
    kelvin = temp_c + 273.15
    for device in _mosfets(circuit):
        device.set_temperature(kelvin)


def _sweep_target(circuit, name: str):
    """The component a ``dc <source>`` sweep drives, matched case-insensitively.

    Returns ``(component, attribute)`` where the attribute is ``"voltage"`` or
    ``"current"`` -- the live property the stamps read, never ``value``.
    """
    from pycircuitsim.models.passive import (                   # noqa: PLC0415
        CurrentSource, VoltageSource)
    wanted = name.lower()
    for comp in circuit.components:
        if comp.name.lower() != wanted:
            continue
        if isinstance(comp, VoltageSource):
            return comp, "voltage"
        if isinstance(comp, CurrentSource):
            return comp, "current"
        raise SimFailure(
            f"Sweep source '{name}' is a {type(comp).__name__}, "
            f"which is not a source")
    raise SimFailure(f"Sweep source '{name}' is not in the circuit")


def _dc_solve(circuit, td: TranslatedDeck, opts: SimOptions,
              guess: Optional[Dict[str, float]], dv_limit: float):
    """One DC solve.  Returns ``(voltages, converged, error_or_None)``.

    Never raises: a diverged point is data.  ``converged`` is ``DCSolver``'s own
    flag AND finiteness -- it is deliberately NOT trusted as evidence of the
    RIGHT root; that is what the operating-point delta is for.
    """
    from pycircuitsim.solver import DCSolver                    # noqa: PLC0415

    solver = DCSolver(
        circuit,
        initial_guess=guess or None,
        use_source_stepping=opts.use_source_stepping,
        max_iterations=opts.max_iterations,
        dv_limit=dv_limit or None,
        reltol=td.options.reltol if td.options.reltol is not None else opts.reltol,
        vntol=td.options.vntol if td.options.vntol is not None else opts.vntol,
    )
    try:
        voltages = solver.solve(skip_header=True)
    except Exception as exc:                        # noqa: BLE001 -- data
        return None, False, f"{type(exc).__name__}: {str(exc).splitlines()[0]}"
    finite = all(np.isfinite(v) and abs(v) < 1e10 for v in voltages.values())
    return voltages, bool(solver._last_solve_converged and finite), None


def _pinned_operating_point(circuit, td: TranslatedDeck, opts: SimOptions,
                            dv_limit: float):
    """DC operating point with the deck's ``.ic`` nodes held, NGSPICE-style.

    NGSPICE's ``.ic`` (no ``uic``) computes the operating point with those nodes
    CONSTRAINED and starts the transient from that constrained solution.  It is
    done here with temporary voltage sources rather than through
    ``DCSolver(force_ic=True)``, which releases the pins and re-solves
    unconstrained -- correct for an SRAM latch, wrong for this.

    Returns ``(voltages, converged, error_or_None)``.
    """
    from pycircuitsim.models.passive import VoltageSource       # noqa: PLC0415

    if not td.ic:
        return _dc_solve(circuit, td, opts,
                         dict(td.nodesets) or None, dv_limit)

    table = _node_table(circuit)
    pins = []
    for node, value in td.ic.items():
        target = table.get(node.lower())
        if target is None:
            continue
        pins.append(VoltageSource(f"_V_ic_{target}", [target, "0"], value))
    circuit.components.extend(pins)
    circuit.invalidate_topology()
    try:
        guess = dict(td.nodesets)
        guess.update(td.ic)
        return _dc_solve(circuit, td, opts, guess, dv_limit)
    finally:
        for pin in pins:
            circuit.components.remove(pin)
        circuit.invalidate_topology()


def simulate(td: TranslatedDeck, plan: AnalysisPlan, work: Path,
             opts: SimOptions) -> SweepResult:
    """Run one :class:`AnalysisPlan` under PyCircuitSim.

    Handles all four plan kinds.  A dc sweep is a continuation: each point is
    seeded from the previous point (the deck's ``.nodeset`` seeds the first),
    which is what NGSPICE does and what the nodesets are for.  A point the
    solver will not stand behind is recorded as ``NaN`` with ``ok=False`` -- so
    a partially converged sweep is still measurable over the points that did
    solve -- while its voltages are still used as the next point's SEED, since
    seeding is not answering.

    ``meta`` carries the honesty fields: wall clock, solved/total point counts,
    the failure count with the first few error texts, the stride, and whether a
    wall-clock budget truncated the run.
    """
    circuit, netlist = build_circuit(td, work)
    rail = _supply_rail(circuit)
    dv_limit = rail if opts.dv_limit is None else opts.dv_limit
    nodes = _node_table(circuit)
    sources = _branch_sources(circuit)
    meta: Dict[str, Any] = {
        "netlist": str(netlist), "stride": opts.stride,
        "dv_limit": dv_limit, "max_iterations": opts.max_iterations,
        "use_source_stepping": opts.use_source_stepping,
        "devices": len(_mosfets(circuit)),
        "nodes": len(nodes), "failures": [], "failed": 0, "flag_failed": 0,
        "truncated_at": None,
    }
    started = time.perf_counter()

    if td.temp_c is not None and plan.kind != "dc_temp":
        _apply_temperature(circuit, td.temp_c)
        meta["temp_c"] = td.temp_c

    if plan.kind == "ac":
        result = _simulate_ac(td, plan, circuit, nodes, opts, dv_limit, meta)
    elif plan.kind in ("dc_source", "dc_temp"):
        result = _simulate_dc(td, plan, circuit, nodes, sources, opts,
                              dv_limit, meta)
    elif plan.kind == "tran":
        result = _simulate_tran(td, plan, circuit, nodes, sources, opts,
                                dv_limit, meta)
    else:
        raise SimFailure(f"Unsupported plan kind {plan.kind!r}")

    result.meta["seconds"] = time.perf_counter() - started
    return result


def _simulate_ac(td: TranslatedDeck, plan: AnalysisPlan, circuit,
                 nodes: Dict[str, str], opts: SimOptions, dv_limit: float,
                 meta: Dict[str, Any]) -> SweepResult:
    """DC operating point, then one complex solve per frequency."""
    from pycircuitsim.solver import ACSolver                    # noqa: PLC0415

    dc_started = time.perf_counter()
    voltages, converged, error = _dc_solve(circuit, td, opts,
                                           dict(td.nodesets) or None, dv_limit)
    meta["dc_seconds"] = time.perf_counter() - dc_started
    meta["dc_converged"] = converged
    if voltages is None:
        raise _fail(meta, f"DC operating point failed: {error}")
    meta["dc_error"] = error
    meta["operating_point"] = {n.lower(): float(v) for n, v in voltages.items()
                               if n not in ("0", "GND")}

    freqs = plan_points(plan, opts.stride)
    raw = ACSolver(circuit, voltages).solve(freqs)
    v = {low: np.asarray(raw[node], dtype=np.complex128)
         for low, node in nodes.items() if node in raw}
    meta["points"] = len(freqs)
    meta["solved"] = len(freqs)
    return SweepResult(kind="ac", x_name="frequency", x=freqs, v=v, i={},
                       ok=None, source="pycircuitsim", meta=meta)


def _simulate_dc(td: TranslatedDeck, plan: AnalysisPlan, circuit,
                 nodes: Dict[str, str], sources: Dict[str, Any],
                 opts: SimOptions, dv_limit: float,
                 meta: Dict[str, Any]) -> SweepResult:
    """A dc sweep, point by point, as a Newton continuation."""
    points = plan_points(plan, opts.stride)
    is_temp = plan.kind == "dc_temp"
    target = attr = None
    if not is_temp:
        assert plan.source is not None
        target, attr = _sweep_target(circuit, plan.source)

    v = {low: np.full(len(points), np.nan) for low in nodes}
    i = {name: np.full(len(points), np.nan) for name in sources}
    ok = np.zeros(len(points), dtype=bool)
    guess: Optional[Dict[str, float]] = dict(td.nodesets) or None
    started = time.perf_counter()

    for idx, point in enumerate(points):
        if opts.max_seconds is not None and \
                time.perf_counter() - started > opts.max_seconds:
            meta["truncated_at"] = idx
            break
        if is_temp:
            _apply_temperature(circuit, float(point))
        else:
            setattr(target, attr, float(point))
        voltages, converged, error = _dc_solve(circuit, td, opts, guess,
                                               dv_limit)
        if voltages is None:
            meta["failed"] += 1
            if len(meta["failures"]) < 5:
                meta["failures"].append({"x": float(point), "error": error})
            continue                        # the row stays NaN: no solution
        # A point the solver disowns is still recorded, because the flag is not
        # trustworthy in EITHER direction and dropping the value would hide
        # which way it went. Measured on the LDO load bench: 0/101 points
        # self-report convergence while every recorded value agrees with
        # NGSPICE to ~2e-5 -- the |ΔV| test, not the physics, is what failed.
        # The reverse (a flag of True on the wrong Newton root) is why
        # `op_delta` and not this flag is the quality verdict.
        for low, node in nodes.items():
            v[low][idx] = voltages.get(node, np.nan)
        for name, comp in sources.items():
            i[name][idx] = comp.calculate_current({})
        ok[idx] = converged
        if not converged:
            meta["flag_failed"] += 1
            if len(meta["failures"]) < 5:
                meta["failures"].append(
                    {"x": float(point),
                     "error": "solver flag: not converged (value kept)"})
        guess = {n: val for n, val in voltages.items()
                 if n not in ("0", "GND")}

    meta["points"] = len(points)
    # `solved` is "produced a finite solution", `flag_ok` is "and the solver
    # said so". They differ, routinely and in both directions; see above.
    meta["solved"] = len(points) - meta["failed"] - (
        len(points) - (meta["truncated_at"] or len(points)))
    meta["flag_ok"] = int(ok.sum())
    x_name = "temp-sweep" if is_temp else (plan.source or "sweep")
    return SweepResult(kind="dc", x_name=x_name, x=points, v=v, i=i, ok=ok,
                       source="pycircuitsim", meta=meta)


def _simulate_tran(td: TranslatedDeck, plan: AnalysisPlan, circuit,
                   nodes: Dict[str, str], sources: Dict[str, Any],
                   opts: SimOptions, dv_limit: float,
                   meta: Dict[str, Any]) -> SweepResult:
    """Operating point, then a fixed-step transient.

    ``.options method=gear maxord=2`` selects the ``gear2`` integrator, which
    keeps BE for step 1 and pins BDF-2 afterwards; every other deck keeps the
    historical BE -> Trap -> BDF-2-on-stiffness ladder.
    """
    from pycircuitsim.solver import TransientSolver             # noqa: PLC0415

    dc_started = time.perf_counter()
    voltages, converged, error = _pinned_operating_point(circuit, td, opts,
                                                         dv_limit)
    meta["dc_seconds"] = time.perf_counter() - dc_started
    meta["dc_converged"] = converged
    meta["dc_error"] = error
    if voltages is None:
        raise _fail(meta, f"Transient operating point failed: {error}")
    meta["operating_point"] = {n.lower(): float(val)
                              for n, val in voltages.items()
                              if n not in ("0", "GND")}

    assert plan.t_step is not None and plan.t_stop is not None
    dt = plan.t_step * opts.stride
    method = "gear2" if (td.options.method or "").startswith("gear") else "auto"
    # Diagnostic override (V7.5.1): compare integrators on one deck without
    # editing it — e.g. trap ringing vs BDF-2 damping on switching-spike
    # extrema. Not a scoring knob; deck `.options method` wins in campaigns.
    method = os.environ.get("PYCIRCUITSIM_BENCH_TRAN_METHOD", method)
    # Diagnostic (V7.5.1): opt-in LTE sub-stepping for the same comparison.
    _substeps = int(os.environ.get("PYCIRCUITSIM_BENCH_TRAN_SUBSTEPS", "1"))
    # V7.5.2: opt-in LTE output refinement (breakpoint-aligned adaptive
    # march, every committed piece emitted) — the fixed-output-grid vs
    # NGSPICE-timestep-control fidelity axis the charge pump exposed.
    _refine = os.environ.get("PYCIRCUITSIM_BENCH_TRAN_REFINE", "0") == "1"
    # V7.5.5 — NGSPICE's tmax rule (dctran: delta never exceeds
    # min(tstep, span/50)) applied to the refine march from the NATIVE
    # tstep, so the piece ceiling is stride-independent. Diagnostic-only
    # (PYCIRCUITSIM_BENCH_TRAN_TMAX=1): NGSPICE-exact, but on a deck like
    # the charge pump's `tran 2p 200n` it forces a 100k-piece march
    # (exactly what NGSPICE does — its 30 s on that deck IS this rule) at
    # pure-Python step cost. The default marching contract stays
    # LTE-governed.
    _refine_max_dt = (min(plan.t_step, plan.t_stop / 50.0)
                      if _refine and os.environ.get(
                          "PYCIRCUITSIM_BENCH_TRAN_TMAX", "0") == "1"
                      else None)
    solver = TransientSolver(
        circuit, t_stop=plan.t_stop, dt=dt,
        initial_guess={n: val for n, val in voltages.items()
                       if n not in ("0", "GND")},
        integration_method=method,
        dv_limit=dv_limit or None,
        reltol=td.options.reltol if td.options.reltol is not None else opts.reltol,
        vntol=td.options.vntol if td.options.vntol is not None else opts.vntol,
        max_substeps=_substeps,
        refine_output=_refine,
        refine_max_dt=_refine_max_dt,
    )
    meta["integration_method"] = method
    meta["dt"] = dt
    meta["refine_output"] = _refine
    meta["refine_max_dt"] = _refine_max_dt
    try:
        raw = solver.solve()
        truncated = None
    except Exception as exc:                        # noqa: BLE001 -- data
        # Partial recovery: the solver tracks the highest committed step so a
        # transient that dies mid-run still yields the waveform up to there.
        meta["failures"].append(
            {"x": None, "error": f"{type(exc).__name__}: "
                                 f"{str(exc).splitlines()[0]}"})
        committed = getattr(solver, "_last_committed_step", 0)
        if committed < 2:
            raise _fail(meta, f"Transient failed at step {committed}: "
                              f"{str(exc).splitlines()[0]}") from exc
        raw = dict(solver._partial_voltages)
        raw["time"] = solver._partial_time
        truncated = committed
        for key in list(raw):
            raw[key] = np.asarray(raw[key])[:committed + 1]
    meta["truncated_at"] = truncated

    times = np.asarray(raw["time"], dtype=np.float64)
    v = {low: np.asarray(raw[node], dtype=np.float64)
         for low, node in nodes.items() if node in raw}
    i = {name.lower(): np.asarray(arr, dtype=np.float64)
         for name, arr in solver.source_currents.items()}
    i = {name: arr[:len(times)] for name, arr in i.items()}
    # `points` is what the run was ASKED for and `solved` what came back, so a
    # transient recovered at step N does not report itself as complete.
    # Refine mode legitimately returns MORE points than asked (the emitted
    # march pieces), so `failed` floors at zero rather than going negative.
    meta["points"] = len(plan_points(plan, opts.stride))
    meta["solved"] = len(times)
    meta["failed"] = max(0, meta["points"] - len(times))
    meta["branch_current_gaps"] = solver._branch_current_gaps
    # Diagnostic (V7.5.5): dump the py-side transient axes to an .npz for
    # waveform-level comparison against the NGSPICE rawfile.
    _dump = os.environ.get("PYCIRCUITSIM_BENCH_DUMP_WAVE", "")
    if _dump:
        np.savez(_dump, time=times,
                 **{f"v_{k}": arr for k, arr in v.items()},
                 **{f"i_{k}": arr for k, arr in i.items()})
    return SweepResult(kind="tran", x_name="time", x=times, v=v, i=i, ok=None,
                       source="pycircuitsim", meta=meta)


# ── Measurement (one code path, both simulators) ─────────────────────────

def measure_result(td: TranslatedDeck, plan: AnalysisPlan,
                   result: SweepResult,
                   seed: Optional[MetricDict] = None) -> MetricDict:
    """Score one sweep exactly the way the reference artifacts are scored.

    The deck's ``.meas`` cards first, then the derived layers the reference adds
    on top of them: the wrap-aware stability metrics for a loop AC bench (whose
    GBW key OVERWRITES the deck's ``.meas`` value -- one definition of the 0 dB
    crossover for both artifact paths) and the full-sweep smoothness metrics for
    a PTAT temperature bench.
    """
    metrics = measure_mod.measure(td.meas, result, params=td.params, seed=seed)
    if td.stability is not None and result.kind == "ac":
        node, gbw_key, suffix = td.stability
        metrics.update(measure_mod.stability_metrics(result, node, gbw_key,
                                                     suffix))
    if _is_ptat(td) and result.kind == "dc":
        metrics.update(measure_mod.sfe_sweep_metrics(result))
    return metrics


def _is_ptat(td: TranslatedDeck) -> bool:
    """A PTAT sensor deck: gated on full-sweep smoothness, not on ``.meas``.

    ``SMCNR_SE_2st_AMP`` is an amplifier shipped in ``sensing_front_end``; it is
    the only design in the category with an AC bench and is gated on that
    instead, exactly as ``finalize.py`` decides.
    """
    return (td.category == "sensing_front_end"
            and td.deck == "tb_dc.cir"
            and not (td.design_dir / "tb_ac.cir").exists())


def _line_tag(deck: str) -> str:
    """``max``/``min`` suffix of an LDO ``tb_line`` deck (``size_ldo`` tags)."""
    return "max" if "max" in deck else "min"


# ── Operating-point comparison ───────────────────────────────────────────

def op_delta(py: Dict[str, float], ng: Dict[str, float],
             top_n: int = 5) -> Dict[str, Any]:
    """Node-by-node operating-point comparison, worst first.

    The field this module exists to report.  Nodes present on only one side are
    counted, not silently dropped: a name mismatch would otherwise make an
    empty comparison look like perfect agreement.
    """
    common = sorted(set(py) & set(ng))
    deltas = [(node, float(py[node]) - float(ng[node])) for node in common]
    deltas.sort(key=lambda item: -abs(item[1]))
    rms = (math.sqrt(sum(d * d for _, d in deltas) / len(deltas))
           if deltas else None)
    return {
        "n_compared": len(deltas),
        "only_pycircuitsim": sorted(set(py) - set(ng)),
        "only_ngspice": sorted(set(ng) - set(py)),
        "worst_node": deltas[0][0] if deltas else None,
        "worst_abs": abs(deltas[0][1]) if deltas else None,
        "rms": rms,
        "top": [{"node": n, "delta": d} for n, d in deltas[:top_n]],
    }


def sweep_delta(py: SweepResult, ng: SweepResult,
                top_n: int = 5) -> Dict[str, Any]:
    """Worst per-point node-voltage deviation over two dc sweeps.

    Stronger than a single operating point: it is an operating-point comparison
    at every solved point.  Only points whose abscissae agree to 1e-6 relative
    are compared, so a strided PyCircuitSim run is compared against the
    NGSPICE points it actually shares.

    Every FINITE point is compared, including ones the solver's own convergence
    flag rejected -- that flag is the thing being audited here, so filtering on
    it would make the audit circular (and, measured on the LDO load bench, would
    discard 101 points that agree with NGSPICE to 2e-5).  ``n_flag_ok`` reports
    how many of the compared points the solver did stand behind.
    """
    common_nodes = sorted(set(py.v) & set(ng.v))
    ng_index: Dict[int, int] = {}
    for py_idx, x in enumerate(py.x):
        tol = 1e-6 * max(1.0, abs(float(x)))
        hits = np.nonzero(np.abs(ng.x - x) <= tol)[0]
        if hits.size:
            ng_index[py_idx] = int(hits[0])
    worst: List[Tuple[str, float, float]] = []
    total = 0
    acc = 0.0
    for node in common_nodes:
        py_arr = np.real(np.asarray(py.v[node])).astype(np.float64)
        ng_arr = np.real(np.asarray(ng.v[node])).astype(np.float64)
        node_worst = 0.0
        node_at = math.nan
        node_points = 0
        for py_idx, ng_idx in ng_index.items():
            a, b = py_arr[py_idx], ng_arr[ng_idx]
            if not (math.isfinite(a) and math.isfinite(b)):
                continue
            delta = abs(a - b)
            node_points += 1
            acc += delta * delta
            if delta > node_worst:
                node_worst, node_at = delta, float(py.x[py_idx])
        total += node_points
        if node_points:
            worst.append((node, node_worst, node_at))
    worst.sort(key=lambda item: -item[1])
    return {
        "n_compared": total,
        "matched_points": len(ng_index),
        "n_flag_ok": (int(np.sum(py.ok)) if py.ok is not None
                      else len(py.x)),
        "only_pycircuitsim": sorted(set(py.v) - set(ng.v)),
        "only_ngspice": sorted(n for n in set(ng.v) - set(py.v)
                               if _INTERNAL_MARK not in n),
        "worst_node": worst[0][0] if worst else None,
        "worst_abs": worst[0][1] if worst else None,
        "rms": math.sqrt(acc / total) if total else None,
        "top": [{"node": n, "delta": d, "at": at} for n, d, at in worst[:top_n]],
    }


def grid_report(py: SweepResult, ng: SweepResult) -> Dict[str, Any]:
    """Do the two simulators agree on the abscissa they solved?"""
    out: Dict[str, Any] = {"py_points": int(len(py.x)),
                           "ng_points": int(len(ng.x)),
                           "max_rel_dev": None}
    if len(py.x) == len(ng.x) and len(py.x):
        denom = np.where(np.abs(ng.x) > 0.0, np.abs(ng.x), 1.0)
        out["max_rel_dev"] = float(np.max(np.abs(py.x - ng.x) / denom))
    return out


# ── One deck, end to end ─────────────────────────────────────────────────

def compare_translated(td: TranslatedDeck, work: Path,
                       opts: SimOptions = SimOptions(),
                       rtol: float = 0.02) -> Dict[str, Any]:
    """Simulate one already-translated deck under both simulators and score it.

    Every plan of the deck runs on both sides.  A deck with two plans is the LDO
    line-regulation bench, whose metrics come from combining the two outward dc
    segments (its decks carry no ``.meas`` cards at all); the ``ng_meas`` column
    for it comes from ONE run of the deck's complete control block, ``echo``
    lines included, so it stays identical to what the reference records.

    Returns:
        A JSON-serialisable dict; see the module docstring for the columns.
    """
    work.mkdir(parents=True, exist_ok=True)
    out: Dict[str, Any] = {
        "schema": SCHEMA_VERSION,
        "tech": td.tech, "category": td.category, "design": td.design,
        "deck": td.deck, "devices": td.devices,
        "control": [plan.control for plan in td.plans],
        "plans": [asdict(plan) for plan in td.plans],
        "translate_warnings": list(td.warnings),
        "options": asdict(opts),
        "pycircuitsim": {"metrics": {}, "seconds": 0.0, "error": None,
                         "sweeps": []},
        "ngspice": {"metrics": {}, "seconds": 0.0, "error": None,
                    "own_meas": {}, "sweeps": []},
        "compare": {}, "op_delta": None, "grid": [], "notes": [],
    }

    # ── NGSPICE ──────────────────────────────────────────────────────────
    ng_sweeps: List[SweepResult] = []
    ng_metrics: MetricDict = {}
    ng_own: MetricDict = {}
    ng_seconds = 0.0
    try:
        for plan in td.plans:
            sweep, own, seconds = ngspice_sweep(td, plan, work, opts.ng_timeout)
            ng_sweeps.append(sweep)
            ng_seconds += seconds
            ng_metrics = measure_result(td, plan, sweep, seed=ng_metrics)
            if len(td.plans) == 1:
                ng_own = own
            out["ngspice"]["sweeps"].append(
                {"kind": plan.kind, "label": plan.label,
                 "points": int(len(sweep.x)), "seconds": seconds,
                 "rawfile": sweep.meta.get("rawfile")})
        if len(td.plans) > 1:
            # The reference runs the whole control block in one pass; its
            # `echo` lines are where the LDO line metrics come from.
            started = time.perf_counter()
            ng_own = _run_ngspice(td.design_dir / td.deck, _full_control(td),
                                  work, f"{Path(td.deck).stem}_ref",
                                  opts.ng_timeout)
            ng_seconds += time.perf_counter() - started
        ng_metrics = _combine_segments(td, ng_sweeps, ng_metrics)
    except Exception as exc:                        # noqa: BLE001 -- data
        out["ngspice"]["error"] = f"{type(exc).__name__}: {exc}"
    out["ngspice"]["metrics"] = ng_metrics
    out["ngspice"]["own_meas"] = ng_own
    out["ngspice"]["seconds"] = ng_seconds

    # ── PyCircuitSim ─────────────────────────────────────────────────────
    py_sweeps: List[SweepResult] = []
    py_metrics: MetricDict = {}
    py_seconds = 0.0
    py_partial_op: Optional[Dict[str, float]] = None
    try:
        for plan in td.plans:
            sweep = simulate(td, plan, work, opts)
            py_sweeps.append(sweep)
            py_seconds += float(sweep.meta.get("seconds", 0.0))
            py_metrics = measure_result(td, plan, sweep, seed=py_metrics)
            out["pycircuitsim"]["sweeps"].append(_sweep_summary(plan, sweep))
        py_metrics = _combine_segments(td, py_sweeps, py_metrics)
    except Exception as exc:                        # noqa: BLE001 -- data
        out["pycircuitsim"]["error"] = f"{type(exc).__name__}: {exc}"
        partial = getattr(exc, "partial_meta", None)
        if partial:
            py_partial_op = partial.get("operating_point")
            out["pycircuitsim"]["partial"] = {
                k: partial.get(k) for k in
                ("dc_seconds", "dc_converged", "dc_error", "failures",
                 "integration_method", "dt", "devices", "nodes")}
    out["pycircuitsim"]["metrics"] = py_metrics
    out["pycircuitsim"]["seconds"] = py_seconds

    # ── Operating-point delta ────────────────────────────────────────────
    try:
        out["op_delta"] = _op_delta_for(td, py_sweeps, ng_sweeps, work, opts,
                                        py_partial_op)
    except Exception as exc:                        # noqa: BLE001 -- data
        out["op_delta"] = {"error": f"{type(exc).__name__}: {exc}"}

    for py_sweep, ng_sweep in zip(py_sweeps, ng_sweeps):
        out["grid"].append(grid_report(py_sweep, ng_sweep))

    # V7.5.3 — grid-matched comparison column. PyCircuitSim simulates the
    # STRIDED grid while NGSPICE always dumps the full one, so extremum/PP
    # metrics differ by the curve's variation over one stride even when the
    # simulators agree at every shared point (measured: HoiLee tb_dc
    # max_hot 2.84 % at stride 25, 1.29e-5 grid-matched — the peak sits at
    # 38.4 C, between the 2.5 C samples). The py-vs-ng column therefore
    # re-measures NGSPICE's sweep ON py's abscissae when a dc sweep is
    # strided; ngspice.metrics and the ng_vs_ngmeas control keep the full
    # dump (the control answers to NGSPICE's own full-grid .meas).
    ng_cmp = ng_metrics
    if (opts.stride > 1 and py_sweeps
            and len(py_sweeps) == len(ng_sweeps)
            and out["pycircuitsim"]["error"] is None
            and out["ngspice"]["error"] is None
            and all(p.kind in ("dc_source", "dc_temp") for p in td.plans)):
        try:
            sub_metrics: MetricDict = {}
            subs: List[SweepResult] = []
            for plan, ng_sw, py_sw in zip(td.plans, ng_sweeps, py_sweeps):
                idx = np.abs(ng_sw.x[None, :]
                             - py_sw.x[:, None]).argmin(axis=1)
                sub = replace(
                    ng_sw, x=ng_sw.x[idx],
                    v={k: arr[idx] for k, arr in ng_sw.v.items()},
                    i={k: arr[idx] for k, arr in ng_sw.i.items()},
                    ok=None if ng_sw.ok is None else ng_sw.ok[idx])
                subs.append(sub)
                sub_metrics = measure_result(td, plan, sub, seed=sub_metrics)
            ng_cmp = _combine_segments(td, subs, sub_metrics)
            out["notes"].append(
                f"py_vs_ng measured on the shared strided grid "
                f"({len(py_sweeps[0].x)} of {len(ng_sweeps[0].x)} points); "
                f"ngspice.metrics and the engine control stay full-grid")
        except Exception as exc:                    # noqa: BLE001 -- data
            out["notes"].append(
                f"grid-matched comparison failed ({type(exc).__name__}: "
                f"{exc}); py_vs_ng uses NGSPICE's full grid")
    out["compare"]["py_vs_ng"] = measure_mod.compare_metrics(
        py_metrics, ng_cmp, rtol=rtol, atol_by_key=METRIC_ATOL)
    out["compare"]["ng_vs_ngmeas"] = measure_mod.compare_metrics(
        ng_metrics, ng_own, rtol=rtol) if ng_own else {}
    out["verdict"] = _verdict(out)
    return out


#: Recovery replaces the monolithic pass only when the primary sweep's worst
#: node error exceeds this fraction of the supply rail.  For scale, on
#: Alfio_RAFFC_Pin_3 (0.65 V) the qualified 25 C solve is off by 114 uV
#: (0.02 %) while the diverged monolithic sweep is off by 9.75 V (1500 %), so
#: any threshold in between separates them; 2 % is one part in fifty of the rail.
RECOVERY_OP_FRACTION: float = 0.02

#: What ``finalize.py``'s narrow third pass exists to recover: the 25 C readings,
#: which need only a two-point window and so survive when the full range does not.
RECOVERY_NARROW_KEYS: Tuple[str, ...] = ("power", "vos25", "vout25", "ivdd25")


class _OpDeltaShape(RuntimeError):
    """``op_delta`` did not carry the key this module gates recovery on."""


def _op_worst(row: Dict[str, Any]) -> Optional[float]:
    """The worst node-voltage error a scored row recorded, if it recorded one.

    ``worst_abs`` is the key both producers write (:func:`op_delta` and
    :func:`sweep_delta`).  An ``op_delta`` that is present but carries no
    recognised key RAISES rather than returning None: reading the wrong key
    silently reports "no error measured", which reads as "the pass was fine" and
    quietly disables recovery on exactly the decks that need it.  That is not a
    hypothetical -- it is the bug this function shipped with.
    """
    delta = row.get("op_delta")
    if not isinstance(delta, dict) or "error" in delta:
        return None                      # no comparison was possible at all
    if "worst_abs" not in delta:
        raise _OpDeltaShape(
            f"op_delta has no 'worst_abs'; keys are {sorted(delta)}")
    worst = delta["worst_abs"]
    return float(worst) if isinstance(worst, (int, float)) else None


def _needs_recovery(row: Dict[str, Any], td: TranslatedDeck) -> Optional[str]:
    """Why the monolithic PyCircuitSim pass is unusable, or None when it is fine.

    Deliberately gated on the operating-point delta rather than on the metrics:
    the diverged monolithic sweep DOES produce a full set of plausible-looking
    numbers (a ``tc`` of 0.014 against NGSPICE's 0.0044), so metric presence
    cannot tell a converged sweep from a diverged one.  The node voltages can.
    """
    if row["pycircuitsim"]["error"]:
        return f"monolithic pass failed: {row['pycircuitsim']['error']}"
    # V7.5.3 — an NGSPICE-side monolithic failure is recovery's own case:
    # the reference flow itself re-runs wide temperature sweeps as two
    # continuations from 25 C, and NGSPICE's 125 C cold start genuinely
    # dies mid-sweep on some decks (Song_DACFC / Qu_LEC tb_dc: "DC:
    # Timestep too small; temp = 45.7"). Both sides are re-scored on the
    # segments, so the comparison stays column-matched. Before the
    # corroboration gate below this was recovered ACCIDENTALLY: the fork
    # trigger fired on the None-vs-number metric entries of the empty
    # NGSPICE column.
    if row["ngspice"]["error"]:
        return f"NGSPICE monolithic pass failed: {row['ngspice']['error']}"
    worst = _op_worst(row)
    if worst is not None:
        supply = float(td.params.get("supply_voltage") or 0.0) or 1.0
        if worst > RECOVERY_OP_FRACTION * supply:
            return (f"monolithic pass operating point off by {worst:.4g} V, "
                    f"over {RECOVERY_OP_FRACTION:.0%} of the {supply:g} V "
                    f"rail")
    # V7.5.0 — branch-fork trigger. The op-delta gate above cannot see a
    # SINGLE ambiguous point: at a first-point branch fork (the 125 C
    # amplifier start has two valid Newton roots) both simulators produce
    # self-consistent sweeps whose shared-grid node voltages agree to
    # microvolts everywhere except the fork, yet the MAX-family metrics
    # differ by the branch gap. A metric disagreement is trusted as a
    # recovery signal ONLY on a temperature sweep (where the outward
    # continuation is defined) and ONLY when the engine control confirms
    # the reading of NGSPICE's own sweep, so it cannot be a
    # measurement-semantics artifact.
    if any(plan.kind == "dc_temp" for plan in td.plans):
        # V7.5.3 — corroboration gate: a bare metric mismatch is NOT fork
        # evidence. HoiLee tb_dc fired this trigger on a strided-extremum
        # artifact (per-point agreement 4.4 uV worst, no fork anywhere) and
        # the recovery segments then traded one grid artifact for another.
        # A real single-point fork leaves per-point evidence: either the
        # compared operating point carries the branch gap (worst_abs at
        # percent-of-rail scale) or one simulator failed to solve the
        # forked point at all (asymmetric point sets).
        delta = row.get("op_delta") or {}
        supply = float(td.params.get("supply_voltage") or 0.0) or 1.0
        asymmetric = bool(delta.get("only_pycircuitsim")
                          or delta.get("only_ngspice"))
        corroborated = asymmetric or (
            worst is not None and worst > 0.01 * supply)
        if not corroborated:
            return None
        eng_rows = row["compare"].get("ng_vs_ngmeas") or {}
        for key, entry in (row["compare"].get("py_vs_ng") or {}).items():
            if entry.get("ok") or key == "sweep_points":
                continue                     # grid size is a stride artifact
            eng = eng_rows.get(key)
            if eng is not None and not eng.get("ok"):
                continue                     # NGSPICE disagrees with itself
            return (f"metric '{key}' disagrees on a dc_temp sweep while the "
                    f"engine control holds and the operating-point delta "
                    f"corroborates (branch fork)")
    return None


def compare_with_recovery(td: TranslatedDeck, work: Path,
                          opts: SimOptions = SimOptions(),
                          rtol: float = 0.02) -> Dict[str, Any]:
    """Score a deck, falling back to the reference's outward-from-25 C recovery.

    A monolithic 165 C sweep can lose its Newton branch at its first point;
    ``finalize.py`` answers that by sweeping OUTWARD from the qualified 25 C
    point and recombining, and :func:`translate.recovery_decks` already emits
    those segments.  The monolithic pass runs first regardless, so a row
    reporting a monolithic sweep really is one, and ``notes`` always records
    which path produced the numbers.

    BOTH simulators are re-scored on the segments, never just PyCircuitSim.
    :func:`measure.recombine_temp_segments` is intentionally bug-compatible with
    the reference -- each segment's deck carries the other segment's window,
    which collapses to the single 25 C point -- so a recombined ``maxval`` sits
    far below the monolithic one (measured: 0.1933828 V versus 0.3699788 V).
    Scoring a recombined column against a monolithic column would therefore
    report a 2x disagreement that is pure bookkeeping. Matching the two columns
    is what keeps a reported difference a real one.

    Returns:
        The monolithic row when it is sound or no recovery exists for this deck,
        otherwise the recovery row, carrying the monolithic row under
        ``recovery.monolithic`` so nothing is discarded.
    """
    row = compare_translated(td, work, opts, rtol=rtol)
    segments = translate.recovery_decks(td)
    reason = _needs_recovery(row, td)
    if not segments or reason is None:
        if segments:
            row["notes"].append("monolithic pass sound; recovery not needed")
        return row

    seg_rows: Dict[str, Dict[str, Any]] = {}
    for segment in segments:
        label = segment.plans[0].label
        # The narrow pass is three points (30/25/20 C) and exists solely to
        # recover the 25 C readings; a stride throws that point away and with it
        # the whole purpose of the segment, so it always runs unstrided.
        seg_opts = replace(opts, stride=1) if label == "narrow" else opts
        seg_rows[label] = compare_translated(segment, work, seg_opts, rtol=rtol)

    if not {"hot", "cold"} <= set(seg_rows):
        row["notes"].append(f"{reason}; recovery unavailable (segments missing)")
        return row

    out = dict(row)
    out["notes"] = list(row["notes"]) + [
        reason,
        "metrics below are the recombined hot/cold recovery segments, for BOTH "
        "simulators; they are NOT the monolithic sweep's",
    ]
    for side in ("pycircuitsim", "ngspice"):
        recombined = measure_mod.recombine_temp_segments(
            seg_rows["hot"][side]["metrics"], seg_rows["cold"][side]["metrics"])
        narrow = seg_rows.get("narrow", {}).get(side, {}).get("metrics", {})
        for key in RECOVERY_NARROW_KEYS:
            if recombined.get(key) is None and narrow.get(key) is not None:
                recombined[key] = narrow[key]
        out[side] = dict(row[side])
        out[side]["metrics"] = recombined
        out[side]["seconds"] = row[side]["seconds"] + sum(
            seg_rows[label][side]["seconds"] for label in seg_rows)
        out[side]["sweeps"] = [summary for label in seg_rows
                               for summary in seg_rows[label][side]["sweeps"]]
        errors = [f"{label}: {seg_rows[label][side]['error']}"
                  for label in seg_rows if seg_rows[label][side]["error"]]
        out[side]["error"] = "; ".join(errors) if errors else None

    out["recovery"] = {
        "used": True,
        "reason": reason,
        "segments": {label: {"control": seg_rows[label]["control"],
                             "op_delta": seg_rows[label]["op_delta"],
                             "verdict": seg_rows[label]["verdict"]}
                     for label in seg_rows},
        "monolithic": {"pycircuitsim": row["pycircuitsim"]["metrics"],
                       "ngspice": row["ngspice"]["metrics"],
                       "op_delta": row["op_delta"],
                       "verdict": row["verdict"]},
    }
    out["op_delta"] = seg_rows["cold"]["op_delta"]
    out["compare"]["py_vs_ng"] = measure_mod.compare_metrics(
        out["pycircuitsim"]["metrics"], out["ngspice"]["metrics"], rtol=rtol,
        atol_by_key=METRIC_ATOL)
    out["compare"]["ng_vs_ngmeas"] = {}
    out["verdict"] = _verdict(out)
    return out


def _full_control(td: TranslatedDeck) -> str:
    """The deck's complete injected control block (all plans, let/echo tail)."""
    return translate.build_controls(td.category, td.design_dir)[td.deck]


def _sweep_summary(plan: AnalysisPlan, sweep: SweepResult) -> Dict[str, Any]:
    """The per-sweep honesty record that lands in the JSON."""
    meta = sweep.meta
    return {
        "kind": plan.kind, "label": plan.label,
        "points": meta.get("points"), "solved": meta.get("solved"),
        "failed": meta.get("failed"), "flag_ok": meta.get("flag_ok"),
        "flag_failed": meta.get("flag_failed"),
        "seconds": meta.get("seconds"), "dc_seconds": meta.get("dc_seconds"),
        "dc_converged": meta.get("dc_converged"),
        "stride": meta.get("stride"), "dv_limit": meta.get("dv_limit"),
        "truncated_at": meta.get("truncated_at"),
        "integration_method": meta.get("integration_method"),
        "dt": meta.get("dt"),
        "branch_current_gaps": meta.get("branch_current_gaps"),
        "failures": meta.get("failures", []),
    }


def _combine_segments(td: TranslatedDeck, sweeps: Sequence[SweepResult],
                      metrics: MetricDict) -> MetricDict:
    """Add the LDO line-regulation metrics when the deck is the two-segment one."""
    if len(sweeps) != 2 or not td.deck.startswith("tb_line"):
        return metrics
    up, down = sweeps
    merged = dict(metrics)
    merged.update(measure_mod.combine_line_segments(up, down, LINE_NODE,
                                                    _line_tag(td.deck)))
    return merged


def _op_delta_for(td: TranslatedDeck, py_sweeps: Sequence[SweepResult],
                  ng_sweeps: Sequence[SweepResult], work: Path,
                  opts: SimOptions,
                  partial_op: Optional[Dict[str, float]] = None
                  ) -> Optional[Dict[str, Any]]:
    """Operating-point delta, from the sweep itself when the sweep carries one.

    A dc sweep's dump IS a per-point operating point, so it gives the strongest
    available check.  An ac/tran deck's dump does not, so NGSPICE is asked for
    an ``op`` and the delta is taken against the operating point PyCircuitSim
    actually linearised (ac) or started from (tran) -- including
    ``partial_op``, the operating point of a run that then died, which is the
    case where this comparison is the entire diagnosis.
    """
    py_op: Optional[Dict[str, float]] = None
    if py_sweeps and ng_sweeps and py_sweeps[0].kind == "dc":
        report = sweep_delta(py_sweeps[0], ng_sweeps[0])
        report["source"] = "per-point-sweep"
        return report
    if py_sweeps:
        py_op = py_sweeps[0].meta.get("operating_point")
    py_op = py_op or partial_op
    if not py_op:
        return None
    report = op_delta(py_op, ngspice_operating_point(td, work, opts.ng_timeout))
    report["source"] = ("ngspice-op-run" if py_sweeps
                        else "ngspice-op-run (failed run's operating point)")
    return report


def _verdict(out: Dict[str, Any]) -> Dict[str, Any]:
    """A compact pass/fail summary of one deck row.

    ``measured`` counts metric keys both simulators produced a number for;
    ``agree`` counts those within tolerance.  ``missing_py`` counts keys NGSPICE
    measured and PyCircuitSim did not -- kept separate and reported because
    ``agree/measured`` alone reads as "0/0, nothing to compare" for a deck that
    actually produced no metrics at all.  ``engine_ok`` is the ng vs ng_meas
    control: False means the measurement layer and NGSPICE disagree on NGSPICE's
    own data and the row's other numbers mean nothing.
    """
    def tally(table: Dict[str, Dict[str, Any]]) -> Tuple[int, int, int, int]:
        both = agree = only_b = only_a = 0
        for entry in table.values():
            has_a = entry["a"] is not None
            has_b = entry["b"] is not None
            if has_a and has_b:
                both += 1
                agree += bool(entry["ok"])
            elif has_b:
                only_b += 1
            elif has_a:
                only_a += 1
        return agree, both, only_b, only_a

    agree, measured, missing_py, extra_py = tally(out["compare"]["py_vs_ng"])
    eng_agree, eng_measured, _, _ = tally(out["compare"]["ng_vs_ngmeas"])
    op = out.get("op_delta") or {}
    return {
        "ran": out["pycircuitsim"]["error"] is None,
        # V7.5.3 — a total NGSPICE failure used to read as ran=True,
        # engine_ok=True (vacuously), 0/0: a row where the REFERENCE
        # produced nothing was not counted as a failure anywhere.
        "ng_ran": out["ngspice"]["error"] is None,
        "measured": measured, "agree": agree,
        "missing_py": missing_py, "extra_py": extra_py,
        "engine_measured": eng_measured, "engine_agree": eng_agree,
        "engine_ok": eng_measured == 0 or eng_agree == eng_measured,
        "op_worst_abs": op.get("worst_abs"),
        "py_seconds": out["pycircuitsim"]["seconds"],
        "ng_seconds": out["ngspice"]["seconds"],
    }


def compare_deck(design_dir: Path, deck: str, *, tech: str, category: str,
                 work: Path, opts: SimOptions = SimOptions(),
                 control: Optional[str] = None,
                 rtol: float = 0.02,
                 recovery: bool = True) -> Dict[str, Any]:
    """Translate one deck and score it under both simulators.

    Args:
        recovery: Allow the outward-from-25 C fallback when a monolithic
            temperature sweep loses its Newton branch (see
            :func:`compare_with_recovery`).  Only the amplifier ``tb_dc.cir``
            bench has such a fallback; every other deck is unaffected.

    Raises:
        TranslateError: If the deck cannot be represented faithfully -- never
            degraded into a plausible wrong answer
    """
    td = translate.translate_deck(design_dir, deck, tech=tech,
                                  category=category, control=control)
    if recovery:
        row = compare_with_recovery(td, work, opts, rtol=rtol)
    else:
        row = compare_translated(td, work, opts, rtol=rtol)
    return _with_altns_fallback(row, td, work, opts, rtol)


def _with_altns_fallback(row: Dict[str, Any], td: TranslatedDeck, work: Path,
                         opts: SimOptions, rtol: float) -> Dict[str, Any]:
    """Score the alternate-nodeset twin when NGSPICE produced nothing.

    Four of the 85 amplifier ``tb_tran.cir`` decks (V7.5.3 sweep: tsmc5
    Qu2017_AZC, tsmc6+tsmc7 Yan_AZ, tsmc16 Leung_DFCFC2) fail NGSPICE's
    transient-op homotopies from the PRIMARY ``.nodeset`` seed — a Newton
    basin artifact, not a deck defect: the shipped seed sits 0.6 mV from the
    true operating point and still fails, while PyCircuitSim solves both
    seeds (metrics agree to 1.7e-7). The corpus ships ``tb_tran_altns.cir``
    for exactly this and the reference runner falls back to it
    (``finalize.py``), so its committed evidence came from the altns seed;
    :func:`translate.altns_deck` existed but was never wired in. The
    returned row keeps the primary deck's name (aggregation keys on it);
    ``notes`` and ``altns`` record which seed actually produced it, and the
    failed primary row is carried, never discarded.
    """
    if row["ngspice"]["error"] is None:
        return row
    alt = translate.altns_deck(td)
    if alt is None:
        return row
    alt_row = compare_translated(alt, work, opts, rtol=rtol)
    if alt_row["ngspice"]["error"] is not None:
        row["notes"].append(
            "ngspice failed on BOTH nodeset seeds "
            f"(altns: {alt_row['ngspice']['error']})")
        return row
    alt_row["notes"].append(
        f"primary .nodeset seed failed in NGSPICE "
        f"({row['ngspice']['error']}); scored the tb_tran_altns.cir twin, "
        f"as the reference runner does")
    alt_row["altns"] = {"used": True, "deck": alt.deck,
                        "reason": row["ngspice"]["error"], "primary": row}
    alt_row["deck"] = td.deck
    return alt_row


def write_result(row: Dict[str, Any], out_dir: Path) -> Path:
    """Write one deck's row as JSON so an 880-deck campaign can aggregate."""
    out_dir.mkdir(parents=True, exist_ok=True)
    path = (out_dir / f"{row['tech']}_{row['category']}_{row['design']}_"
                      f"{Path(row['deck']).stem}.json")
    path.write_text(json.dumps(row, indent=2, default=str))
    return path


# ── CLI ──────────────────────────────────────────────────────────────────

def _designs(root: Path, tech: str, category: str) -> List[Path]:
    """Every built design of one category, in sorted order."""
    cdir = root / f"designs_{tech.lower()}" / category
    if not cdir.is_dir():
        raise SimFailure(f"No such category directory: {cdir}")
    return [d for d in sorted(cdir.iterdir())
            if d.is_dir() and (d / "netlist.spice").exists()]


def _decks_of(category: str, design_dir: Path) -> List[str]:
    """Deck names of one design that exist on disk, in table order."""
    return [deck for deck in translate.build_controls(category, design_dir)
            if (design_dir / deck).exists() and deck != "tb_tran_altns.cir"]


def _print_row(row: Dict[str, Any]) -> None:
    """One line per deck plus the per-metric table."""
    verdict = row["verdict"]
    head = (f"{row['tech']}/{row['category']}/{row['design']}/{row['deck']}")
    print(f"\n=== {head} ===")
    for side in ("pycircuitsim", "ngspice"):
        error = row[side]["error"]
        print(f"  {side:13s} {row[side]['seconds']:8.2f}s"
              + (f"  ERROR {error}" if error else ""))
    for summary in row["pycircuitsim"]["sweeps"]:
        print(f"    py {summary['kind']:9s} points={summary['points']} "
              f"solved={summary['solved']} no_solution={summary['failed']} "
              f"flag_ok={summary['flag_ok']} "
              f"dc_conv={summary['dc_converged']} stride={summary['stride']} "
              f"truncated={summary['truncated_at']}")
        for failure in summary["failures"]:
            print(f"      FAIL at x={failure['x']}: {failure['error']}")
    op = row.get("op_delta") or {}
    if op.get("worst_abs") is not None:
        print(f"  op_delta ({op.get('source')}): worst "
              f"{op['worst_abs']:.6g} V at {op['worst_node']}, rms "
              f"{op['rms']:.3g} V over {op['n_compared']} comparisons")
    elif op:
        print(f"  op_delta: {op}")
    for grid in row["grid"]:
        print(f"  grid: py={grid['py_points']} ng={grid['ng_points']} "
              f"max_rel_dev={grid['max_rel_dev']}")

    table = row["compare"]["py_vs_ng"]
    engine = row["compare"]["ng_vs_ngmeas"]
    print(f"  {'metric':26s} {'pycircuitsim':>15s} {'ngspice':>15s} "
          f"{'rel':>10s}  {'ng_meas':>15s} {'eng_rel':>9s}")
    for key in sorted(table):
        entry = table[key]
        eng = engine.get(key, {})
        print(f"  {key:26s} {_fmt(entry['a']):>15s} {_fmt(entry['b']):>15s} "
              f"{_fmt(entry['rel'], '.3e'):>10s}  "
              f"{_fmt(eng.get('b')):>15s} {_fmt(eng.get('rel'), '.1e'):>9s}"
              + ("" if entry["ok"] else "  <-- differs"))
    print(f"  VERDICT agree {verdict['agree']}/{verdict['measured']}, "
          f"missing_py {verdict['missing_py']}, "
          f"engine {verdict['engine_agree']}/{verdict['engine_measured']}, "
          f"py {verdict['py_seconds']:.1f}s ng {verdict['ng_seconds']:.1f}s")


def _fmt(value: Any, spec: str = ".6g") -> str:
    if value is None:
        return "-"
    try:
        return format(float(value), spec)
    except (TypeError, ValueError):
        return str(value)


def main(argv: Optional[Sequence[str]] = None) -> int:
    """CLI: one deck, one design, or a whole category."""
    parser = argparse.ArgumentParser(
        description="Score AnalogGym decks: PyCircuitSim vs NGSPICE "
                    "(BSIM-CMG LEVEL=72 both sides).")
    parser.add_argument("--root", type=Path, default=BENCH_ROOT,
                        help="tree holding designs_tsmc* (default: %(default)s)")
    parser.add_argument("--tech", default="tsmc5",
                        help="tech tag, e.g. tsmc5 (default: %(default)s)")
    parser.add_argument("--category", required=True, choices=sorted(CONTROLS),
                        help="AnalogGym category")
    parser.add_argument("--design", default=None,
                        help="one design directory name (default: all)")
    parser.add_argument("--deck", default=None,
                        help="one deck, e.g. tb_gain.cir (default: all)")
    parser.add_argument("--out", type=Path, default=None,
                        help="JSON output directory "
                             "(default: <root>/pycircuitsim_bench_results)")
    parser.add_argument("--work", type=Path, default=None,
                        help="scratch directory for netlists/rawfiles "
                             "(default: <out>/work)")
    parser.add_argument("--stride", type=int, default=1,
                        help="keep every Nth sweep point / multiply the "
                             "transient dt by N (default: 1)")
    parser.add_argument("--max-seconds", type=float, default=None,
                        help="wall-clock budget per PyCircuitSim dc sweep; "
                             "the run truncates and says so")
    parser.add_argument("--dv-limit", type=float, default=None,
                        help="per-iteration |dV| cap in volts "
                             "(default: one supply rail; 0 disables)")
    parser.add_argument("--max-iterations", type=int,
                        default=DEFAULT_MAX_ITERATIONS,
                        help="NR budget per DC point (default: %(default)s)")
    parser.add_argument("--source-stepping", action="store_true",
                        help="enable source-stepping homotopy (measured: "
                             "25s slower, same answer, once dv_limit is on)")
    parser.add_argument("--solver-reltol", type=float, default=NGSPICE_RELTOL,
                        help="NR relative tolerance (default: NGSPICE's "
                             "%(default)s; a deck's .options still wins)")
    parser.add_argument("--solver-vntol", type=float, default=NGSPICE_VNTOL,
                        help="NR absolute voltage tolerance in volts "
                             "(default: NGSPICE's %(default)s)")
    parser.add_argument("--ng-timeout", type=float, default=1800.0,
                        help="NGSPICE timeout in seconds (default: %(default)s)")
    parser.add_argument("--rtol", type=float, default=0.02,
                        help="metric agreement tolerance (default: %(default)s)")
    parser.add_argument("--no-recovery", action="store_true",
                        help="do not fall back to the outward-from-25 C "
                             "segments when a monolithic temperature sweep "
                             "loses its Newton branch (amplifier tb_dc only)")
    args = parser.parse_args(argv)
    _pin_design_tree(args.root, args.tech)

    out_dir = args.out or (args.root / "pycircuitsim_bench_results")
    work_root = args.work or (out_dir / "work")
    opts = SimOptions(
        dv_limit=args.dv_limit, max_iterations=args.max_iterations,
        use_source_stepping=args.source_stepping,
        reltol=args.solver_reltol, vntol=args.solver_vntol,
        stride=args.stride, max_seconds=args.max_seconds,
        ng_timeout=args.ng_timeout)

    designs = ([args.root / f"designs_{args.tech.lower()}" / args.category
                / args.design] if args.design
               else _designs(args.root, args.tech, args.category))

    failures = 0
    for design_dir in designs:
        decks = [args.deck] if args.deck else _decks_of(args.category,
                                                        design_dir)
        for deck in decks:
            work = work_root / args.tech.lower() / design_dir.name
            try:
                row = compare_deck(design_dir, deck, tech=args.tech.lower(),
                                   category=args.category, work=work,
                                   opts=opts, rtol=args.rtol,
                                   recovery=not args.no_recovery)
            except Exception as exc:                # noqa: BLE001 -- reported
                failures += 1
                print(f"\n=== {args.tech}/{args.category}/{design_dir.name}/"
                      f"{deck} ===\n  TRANSLATE/RUN ERROR "
                      f"{type(exc).__name__}: {exc}")
                continue
            _print_row(row)
            write_result(row, out_dir)
            if not row["verdict"]["ran"] or not row["verdict"]["ng_ran"]:
                failures += 1
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
